version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: specforge-postgres
    environment:
      POSTGRES_USER: specforge
      POSTGRES_PASSWORD: specforge123
      POSTGRES_DB: specforge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U specforge"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
